/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.DetailCutiController;
import entities.DetailCuti;
import java.awt.print.Book;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.MyConnection;

    
 /**
 *
 * @author Simbok_pc
 */
public class DetailCutiView extends javax.swing.JInternalFrame {

    private DetailCutiController detailCutiController;
    
    /**
     * Creates new form DetailCutiView
     */
    public DetailCutiView() {
        initComponents();
        this.detailCutiController = new DetailCutiController(new MyConnection().getConnection());
        bindingTable();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailCuti = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDetCutiID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCutiID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKaryID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLamaCuti = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblDetailCuti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetailCuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailCutiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetailCuti);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Cuti"));

        jLabel1.setText("Detail Cuti ID");

        jLabel2.setText("Cuti ID");

        txtCutiID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCutiIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Karyawan ID");

        jLabel4.setText("Status");

        jLabel5.setText("Lama Cuti");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDetCutiID)
                        .addComponent(txtCutiID)
                        .addComponent(txtKaryID)
                        .addComponent(txtLamaCuti, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDrop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDetCutiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCutiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtKaryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtLamaCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnDrop))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCutiIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCutiIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCutiIDActionPerformed

    /**
     * fungsi yang digunakan untuk menyimpan data ketika menekan tombol save
     * @param evt 
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean flag = this.detailCutiController.save(txtDetCutiID.getText(), txtCutiID.getText(), txtKaryID.getText(),
                txtLamaCuti.getText(), txtStatus.getText());
       String message = "Failed to save data...";
        if (flag){
            message = "Success to save data...";
        }
        JOptionPane.showMessageDialog(this, message, "Allert / Notification", 
                JOptionPane.INFORMATION_MESSAGE);
        
        bindingTable();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * fungsi yang digunakan untuk menyimpan data ketika menekan tombol edit
     * @param evt 
     */
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        boolean flag = this.detailCutiController.save(txtDetCutiID.getText(), txtCutiID.getText(), txtKaryID.getText(),
                txtLamaCuti.getText(), txtStatus.getText());
        String message = "Failed to edit data";
        if (flag){
            message = "Success to edit data";
        }
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * fungsi yang digunakan untuk menghapus data ketika menekan tombol drop
     * @param evt 
     */
    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        String message = "Failed to edit data...";
        int flag = JOptionPane.showConfirmDialog(this, "Tenane?", "APA KOE YAKIN MEH NGEHAPUS?", 
                JOptionPane.YES_NO_OPTION);
        if (flag == 0){
            if (detailCutiController.drop(txtDetCutiID.getText())){
                message = "Success to drop data...";
            }
            JOptionPane.showMessageDialog(this, message, "Notification", 
                    JOptionPane.QUESTION_MESSAGE);
        }
        bindingTable();
        reset();
    }//GEN-LAST:event_btnDropActionPerformed

    /**
     * fungsi yang digunakan untuk menampilkan data ke text filed ketika memilih data
     * @param evt 
     */
    private void tblDetailCutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailCutiMouseClicked
        int row = tblDetailCuti.getSelectedRow();
        txtDetCutiID.setText(tblDetailCuti.getValueAt(row, 0).toString());
        txtCutiID.setText(tblDetailCuti.getValueAt(row, 1).toString());
        txtKaryID.setText(tblDetailCuti.getValueAt(row, 2).toString());
        txtLamaCuti.setText(tblDetailCuti.getValueAt(row, 3).toString());
        txtStatus.setText(tblDetailCuti.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_tblDetailCutiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetailCuti;
    private javax.swing.JTextField txtCutiID;
    private javax.swing.JTextField txtDetCutiID;
    private javax.swing.JTextField txtKaryID;
    private javax.swing.JTextField txtLamaCuti;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    /**
     * fungsi yang digunakan untuk menampilkan tabel data cuti khusus
     */
    public void bindingTable() {
        String[] header = {"Detail Cuti ID", "Cuti ID", "Karyawan ID", "Lama Cuti", "Status"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (DetailCuti detailCuti : detailCutiController.binding()) {
            Object[] detailCuti1 = {
                detailCuti.getDetailCutiId(), detailCuti.getCutiId(), detailCuti.getKaryawanId(), detailCuti.getLamaCuti(),
                detailCuti.getStatusCuti()
            };
            defaultTableModel.addRow(detailCuti1);
        }
        tblDetailCuti.setModel(defaultTableModel);

    }

    /**
     * fungsi yang digunakan untuk membersihkan data ketika menyimpan atau menghapus data
     */
    public void reset() {
        txtDetCutiID.setText("");
        txtCutiID.setText("");
        txtKaryID.setText("");
        txtLamaCuti.setText("");
        txtStatus.setText("");
    }

}
