/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.JabatanController;
import controllers.KaryawanController;
import entities.Jabatan;
import entities.Karyawan;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.MyConnection;

/**
 *
 * @author AINAN-Gaul
 */
public class KaryawanView extends javax.swing.JInternalFrame {

    private KaryawanController karyawanController;
    private JabatanController jabatanController;

    /**
     * Creates new form KaryawanView
     */
    public KaryawanView() {
        initComponents();
        this.karyawanController = new KaryawanController(new MyConnection().getConnection());
        this.jabatanController = new JabatanController(new MyConnection().getConnection());
        //this.comboJabatan();
        bindingTable();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCategoryKaryawan = new javax.swing.JComboBox<>();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputKaryawanId = new javax.swing.JTextField();
        inputNamaKaryawan = new javax.swing.JTextField();
        inputAlamat = new javax.swing.JTextField();
        cmbJabatan = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputJatah = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Karyawan");

        cmbCategoryKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "karyawan_id", "nama_karyawan", "email", "alamat", "jatah_cuti", "jabatan_id" }));
        cmbCategoryKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryKaryawanActionPerformed(evt);
            }
        });

        btnSearch.setText("Find");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Karyawan"));

        jLabel1.setText("ID Karyawan");

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jabatan");

        cmbJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJabatanActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDrop.setText("Delete");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        jLabel6.setText("Jatah Cuti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNamaKaryawan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputKaryawanId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputAlamat)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(inputJatah)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDrop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputKaryawanId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(inputJatah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrop)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbCategoryKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoryKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean flag = this.karyawanController.save(inputKaryawanId.getText(), Integer.toString(cmbJabatan.getSelectedIndex()), inputNamaKaryawan.getText(), inputEmail.getText(), inputAlamat.getText(), Integer.parseInt(inputJatah.getText()));
        String messege = "Failed to save data!";
        if (flag) {
            messege = "Success to save data, congratulation!";
        }
        JOptionPane.showMessageDialog(this, messege, "Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String messege = "Failed to edit data.";
        if (karyawanController.edit(inputKaryawanId.getText(), Integer.toString(cmbJabatan.getSelectedIndex()), inputNamaKaryawan.getText(), inputEmail.getText(), inputAlamat.getText(), Integer.parseInt(inputJatah.getText()))) {
            messege = "Success to edit data, congratulation!";
        }
        JOptionPane.showMessageDialog(this, messege, "Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        String messege = "Failed to delete data.";
        int flag = JOptionPane.showConfirmDialog(this, "Are you sure want to delete?", "Alert", JOptionPane.YES_NO_OPTION);
        if (flag == 0) {
            if (karyawanController.drop(inputKaryawanId.getText())) {
                messege = "Success to delete data, congratulation!";
            }
            JOptionPane.showMessageDialog(this, messege, "Notification", JOptionPane.QUESTION_MESSAGE);
        }
        bindingTable();
        reset();
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String category = cmbCategoryKaryawan.getSelectedItem().toString();
        String data = inputSearch.getText();
        searchTable(category, data);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        int row = tblKaryawan.getSelectedRow();
        inputKaryawanId.setText(tblKaryawan.getValueAt(row, 0).toString());
        inputNamaKaryawan.setText(tblKaryawan.getValueAt(row, 1).toString());
        inputEmail.setText(tblKaryawan.getValueAt(row, 2).toString());
        inputAlamat.setText(tblKaryawan.getValueAt(row, 3).toString());
        inputJatah.setText(tblKaryawan.getValueAt(row, 4).toString());
        cmbJabatan.setSelectedItem(tblKaryawan.getValueAt(row, 5).toString());
        bindingTable();
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void cmbJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJabatanActionPerformed

    private void cmbCategoryKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JComboBox<String> cmbCategoryKaryawan;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputJatah;
    private javax.swing.JTextField inputKaryawanId;
    private javax.swing.JTextField inputNamaKaryawan;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKaryawan;
    // End of variables declaration//GEN-END:variables

    public void bindingTable() {
        String[] header = {"ID Karyawan", "Nama Karyawan", "Email", "Alamat", "Jatah Cuti", "Jabatan"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (Karyawan karyawan : karyawanController.binding("karyawan_id", "asc")) {
            Object[] karyawan1 = {
                karyawan.getKaryawanId(), karyawan.getNamaKaryawan(), karyawan.getEmail(), karyawan.getAlamat(), karyawan.getJatahCuti(), karyawan.getJabatanId()
            };
            this.cmbJabatan.addItem(karyawan1[5].toString());
            defaultTableModel.addRow(karyawan1);
        }
        tblKaryawan.setModel(defaultTableModel);
    }

    public void searchTable(String category, String data) {
        String[] header = {"ID Karyawan", "Nama Karyawan", "Email", "Alamat", "Jatah Cuti", "Jabatan"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (Karyawan karyawan : karyawanController.find(category, data)) {
            Object[] karyawan1 = {
                karyawan.getKaryawanId(), karyawan.getNamaKaryawan(), karyawan.getEmail(), karyawan.getAlamat(), karyawan.getJatahCuti(), karyawan.getJabatanId()
            };
//            this.cmbJabatan.addItem(karyawan1[5].toString());
            defaultTableModel.addRow(karyawan1);
        }
        tblKaryawan.setModel(defaultTableModel);
    }
    
    public void loadJabatanComboBox(JComboBox comboBox,String[] header){
        comboBox.removeAllItems();
        for (String string : header) {
            comboBox.addItem(string);
        }
    }

//    public void tampilJabatanCmb(){
//        for (Jabatan jabatan : jabatanController.find(category, data)) {
//            Object[] karyawan1 = {
//                karyawan.getKaryawanId(), karyawan.getNamaKaryawan(), karyawan.getEmail(), karyawan.getAlamat(), karyawan.getJatahCuti(), karyawan.getJabatanId()
//            };
//            defaultTableModel.addRow(karyawan1);
//        }
//        this.loadJabatanComboBox(cmbJabatan, );
//    }
    
    
    public void reset() {
        inputKaryawanId.setText("");
        inputNamaKaryawan.setText("");
        inputAlamat.setText("");
        inputEmail.setText("");
        inputJatah.setText("");
    }

    public void comboJabatan() {
        String jabatan1 = "";
        for (Jabatan jabatan : jabatanController.bindingSort("jabatan_id", "asc")) {
            jabatan1 = jabatan.getJabatanId();
        }
        cmbJabatan.setSelectedItem(jabatan1);
    }

    public String getIdfromComboBox(List<Jabatan> datas, int index) {
        return datas.get(index).toString();
    }

    public void loadDetails(List<Jabatan> datas, int index) {
        for (Jabatan data : datas) {
            cmbJabatan.addItem(data.getJabatanId());
        }
    }

//    public void loadRegion() {
//        this.loadDetails(cmbRegion, new RegionController(connection).binding(), 1);
//    }
}
